export const actionType = {
    SET_USER: "SET_USER",
    SET_ALL_USERS: "SET_ALL_USERS",
    SET_ALL_ARTISTS: "SET_ALL_ARTISTS",
    SET_ALL_SONGS: "SET_ALL_SONGS",
    SET_ALL_ALBUMS: "SET_ALL_ALBUMS",
    SET_ISSONG_PLAYING: "SET_ISSONG_PLAYING",
    SET_SONG_INDEX: "SET_SONG_INDEX",
    SET_SELECTED_CHAT: "SET_SELECTED_CHAT",
    SET_ALL_CHATS:"SET_ALL_CHATS",
    SET_MESSAGES: "SET_MESSAGES",
    SET_REQUEST:"SET_REQUEST",
};